console.log("hello world")
console.log(document.body)
console.log(document.body.firstChild)
console.log(document.body.firstElementChild)
console.log(document.body.firstElementChild.children)
console.log(document.body.childNodes)
console.log(document.body.childNodes[3].childNodes)
console.log(document.body.childNodes[3].firstChild)
console.log(document.body.childNodes[3].lastChild)
console.log(document.body.childNodes[3].firstElementChild)
console.log(document.body.childNodes[3].lastElementChild)
console.log(document.body.childNodes[3].firstElementChild.parentElement)
console.log(document.body.childNodes[3].children)
console.log(document.body.childNodes[3].children[0])
console.log(document.body.childNodes[3].children[2])
console.log(document.body.childNodes[3].children[0].nextElementSibling)
console.log(document.body.childNodes[3].children[3].previousElementSibling)
console.log(document.body.childNodes[3].children[3].previousSibling)


